server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/steam-like-app-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:3429}

  servlet:
    multipart:
      enabled: true
      location: images/
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    database: postgresql

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    drop-first: true
